name: Build & publish
on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'

jobs:
  build_and_publish:
    name: Build & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check and build
        run: ./gradlew -Pversion=${GITHUB_REF:11} build
      - name: Publish to Maven
        run: ./gradlew -Pversion=${GITHUB_REF:11} publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
